# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_num', models.IntegerField(blank=True, null=True)),
                ('species', models.CharField(max_length=200)),
                ('type1', models.CharField(max_length=200)),
                ('type2', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
